# Pull Request Labeler Github Action Configuration: https://github.com/marketplace/actions/labeler
jdbc:
  - changed-files:
    - any-glob-to-any-file: 'client/trino-jdbc/**'

bigquery:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-bigquery/**'

delta-lake:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-delta-lake/**'

hive:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-hive/**'

hudi:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-hudi/**'

iceberg:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-iceberg/**'

mongodb:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-mongodb/**'

mysql:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-mysql/**'

opensearch:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-opensearch/**'

oracle:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-oracle/**'

pinot:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-pinot/**'

postgresql:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-postgresql/**'

prometheus:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-prometheus/**'

redis:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-redis/**'

redshift:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-redshift/**'

singlestore:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-singlestore/**'

snowflake:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-snowflake/**'

sqlserver:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-sqlserver/**'

vertica:
  - changed-files:
    - any-glob-to-any-file: 'plugin/trino-vertica/**'

docs:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'

release-notes:
  - changed-files:
    - any-glob-to-any-file: ['docs/src/main/sphinx/release/**', 'docs/src/main/sphinx/release.rst']

ui:
  - changed-files:
    - any-glob-to-any-file: 'core/trino-web-ui/**'
